apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: Novo deploy, teste de flux still
spec:
  replicas: 2
  template:
    metadata:
      labels:
        editor: vscode
    spec:
      containers:
      - name: busybox
        image: busybox